tags:
  name: Admin Routes
  description: Routes specified for admin use after logging in as admin.

/admin/users:
  get:
    summary: Lists all registered users
    tags: [Admin Routes]
    security:
      - bearerAuth: []
    responses:
      '200':
        description: Retrieved all registered users
        content:
          application/json:
            schema:
              type: object
              properties:
                status:
                  type: string
                  enum: ['true', 'false']
                  description: Whether the request was successful or not
                message:
                  type: string
                  description: Description of the response
                data:
                  type: object
                  properties:
                    users:
                      type: array
                      items:
                        $ref: '#/components/schemas/User'
      '400':
        description: |
          **Bad Request**  
          *Possible Reasons:*
          - Missing token: Please authorize with a jwt token.
      '401':
        description: |
          **Unauthorized**  
          *Possible Reasons:*
          - Invalid token: Try with a different jwt token.
      '403':
        description: |
          **Forbidden**  
          *Possible Reasons:*
          - Admin authorization failed: Use a token with admin privilege.
      '404':
        description: |
          **Not Found**  
          *Possible Reasons:*
          - User not found: Try with a different jwt token.
          - Path is incorrect: Check API path and try again.
      '405':
        description: |
          **Method Not Allowed**  
          *Possible Reasons:*
          - Method is not allowed: Check HTTP method and try again.
      '500':
        description: |
          **Internal Server Error**  
          *Possible Reasons:*
          - Can't connect to server: Check the connection
          - Other server errors
  post:
    summary: Register a new user
    requestBody:
      description: Details of the new user
      required: 'true'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/User Registration and Updation (Admin)'
    tags: [Admin Routes]
    security:
      - bearerAuth: []
    responses:
      '201':
        description: Registration successful
        content:
          application/json:
            schema:
              type: object
              properties:
                status:
                  type: string
                  enum: ['true', 'false']
                  description: Whether the request was successful or not
                message:
                  type: string
                  description: Description of the response
                data:
                  type: object
                  properties:
                    user:
                      $ref: '#/components/schemas/User'
      '400':
        description: |
          **Bad Request**  
          *Possible Reasons:*
          - Missing token: Please authorize with a jwt token.
      '401':
        description: |
          **Unauthorized**  
          *Possible Reasons:*
          - Invalid token: Try with a different jwt token.
      '403':
        description: |
          **Forbidden**  
          *Possible Reasons:*
          - Admin authorization failed: Use a token with admin privilege.
      '404':
        description: |
          **Not Found**  
          *Possible Reasons:*
          - Path is incorrect: Check API path and try again.
      '405':
        description: |
          **Method Not Allowed**  
          *Possible Reasons:*
          - Method is not allowed: Check HTTP method and try again.
      '409':
        description: |
          **Conflict**  
          *Possible Reasons:*
          - Email has already been registered: Try using a different email.
      '422':
        description: |
          **Unprocessable Entity**  
          *Possible Reasons:*
          - Validation failed: Try checking the request body.
      '500':
        description: |
          **Internal Server Error**  
          *Possible Reasons:*
          - Can't connect to server: Check the connection
          - Other server errors

/admin/users/{userId}:
  get:
    summary: Get user details by user ID
    tags: [Admin Routes]
    security:
      - bearerAuth: []
    parameters:
      - in: path
        name: userId
        required: 'true'
        description: ID of the user
        schema:
          type: integer
    responses:
      '200':
        description: User details retrieved successfully
        content:
          application/json:
            schema:
              type: object
              properties:
                status:
                  type: string
                  enum: ['true', 'false']
                  description: Whether the request was successful or not
                message:
                  type: string
                  description: Description of the response
                data:
                  type: object
                  properties:
                    user:
                      $ref: '#/components/schemas/User'
      '400':
        description: |
          **Bad Request**  
          *Possible Reasons:*
          - Missing token: Please authorize with a jwt token.
          - Invalid userId in path: Try using a different userId and check if it is of number type.
      '401':
        description: |
          **Unauthorized**  
          *Possible Reasons:*
          - Invalid token: Try with a different jwt token.
      '403':
        description: |
          **Forbidden**  
          *Possible Reasons:*
          - Admin authorization failed: Use a token with admin privilege.
      '404':
        description: |
          **Not Found**  
          *Possible Reasons:*
          - User not found: Try with a different jwt token.
          - Path is incorrect: Check API path and try again.
      '405':
        description: |
          **Method Not Allowed**  
          *Possible Reasons:*
          - Method is not allowed: Check HTTP method and try again.
      '409':
        description: |
          **Conflict**  
          *Possible Reasons:*
          - Email has already been registered: Try using a different email.
      '422':
        description: |
          **Unprocessable Entity**  
          *Possible Reasons:*
          - Validation failed: Try checking the request body.
      '500':
        description: |
          **Internal Server Error**  
          *Possible Reasons:*
          - Can't connect to server: Check the connection
          - Other server errors
  put:
    summary: Update all user details by user ID
    requestBody:
      description: Modified user details. Required fields cannot be omitted.
      required: 'true'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/User Registration and Updation (Admin)'
    tags: [Admin Routes]
    security:
      - bearerAuth: []
    parameters:
      - in: path
        name: userId
        required: 'true'
        description: ID of the user
        schema:
          type: integer
    responses:
      '200':
        description: User details updated successfully
        content:
          application/json:
            schema:
              type: object
              properties:
                status:
                  type: string
                  enum: ['true', 'false']
                  description: Whether the request was successful or not
                message:
                  type: string
                  description: Description of the response
                data:
                  type: object
                  properties:
                    user:
                      $ref: '#/components/schemas/User'
      '400':
        description: |
          **Bad Request**  
          *Possible Reasons:*
          - Missing token: Please authorize with a jwt token.
          - Invalid userId in path: Try using a different userId and check if it is of number type.
      '401':
        description: |
          **Unauthorized**  
          *Possible Reasons:*
          - Invalid token: Try with a different jwt token.
      '403':
        description: |
          **Forbidden**  
          *Possible Reasons:*
          - Admin authorization failed: Use a token with admin privilege.
      '404':
        description: |
          **Not Found**  
          *Possible Reasons:*
          - User not found: Try with a different jwt token.
          - Path is incorrect: Check API path and try again.
      '405':
        description: |
          **Method Not Allowed**  
          *Possible Reasons:*
          - Method is not allowed: Check HTTP method and try again.
      '409':
        description: |
          **Conflict**  
          *Possible Reasons:*
          - Email has already been registered: Try using a different email.
      '422':
        description: |
          **Unprocessable Entity**  
          *Possible Reasons:*
          - Validation failed: Try checking the request body.
      '500':
        description: |
          **Internal Server Error**  
          *Possible Reasons:*
          - Can't connect to server: Check the connection
          - Other server errors
  patch:
    summary: Update user details partially by user ID
    tags: [Admin Routes]
    requestBody:
      description: Details of the user to be updated. Can omit fields which need not be updated.
      required: 'true'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/User Partial Updation (Admin)'
    security:
      - bearerAuth: []
    parameters:
      - in: path
        name: userId
        required: 'true'
        description: ID of the user
        schema:
          type: integer
    responses:
      '200':
        description: User details retrieved successfully
        content:
          application/json:
            schema:
              type: object
              properties:
                status:
                  type: string
                  enum: ['true', 'false']
                  description: Whether the request was successful or not
                message:
                  type: string
                  description: Description of the response
                data:
                  type: object
                  properties:
                    user:
                      $ref: '#/components/schemas/User'
      '400':
        description: |
          **Bad Request**  
          *Possible Reasons:*
          - Missing token: Please authorize with a jwt token.
          - Invalid userId in path: Try using a different userId and check if it is of number type.
      '401':
        description: |
          **Unauthorized**  
          *Possible Reasons:*
          - Invalid token: Try with a different jwt token.
      '403':
        description: |
          **Forbidden**  
          *Possible Reasons:*
          - Admin authorization failed: Use a token with admin privilege.
      '404':
        description: |
          **Not Found**  
          *Possible Reasons:*
          - User not found: Try with a different jwt token.
          - Path is incorrect: Check API path and try again.
      '405':
        description: |
          **Method Not Allowed**  
          *Possible Reasons:*
          - Method is not allowed: Check HTTP method and try again.
      '409':
        description: |
          **Conflict**  
          *Possible Reasons:*
          - Email has already been registered: Try using a different email.
      '422':
        description: |
          **Unprocessable Entity**  
          *Possible Reasons:*
          - Validation failed: Try checking the request body.
      '500':
        description: |
          **Internal Server Error**  
          *Possible Reasons:*
          - Can't connect to server: Check the connection
          - Other server errors
  delete:
    summary: Get user details by user ID
    tags: [Admin Routes]
    security:
      - bearerAuth: []
    parameters:
      - in: path
        name: userId
        required: 'true'
        description: ID of the user
        schema:
          type: integer
    responses:
      '200':
        description: User deleted successfully
        content:
          application/json:
            schema:
              type: object
              properties:
                status:
                  type: string
                  enum: ['true', 'false']
                  description: Whether the request was successful or not
                message:
                  type: string
                  description: Description of the response
      '400':
        description: |
          **Bad Request**  
          *Possible Reasons:*
          - Missing token: Please authorize with a jwt token.
          - Invalid userId in path: Try using a different userId and check if it is of number type.
      '401':
        description: |
          **Unauthorized**  
          *Possible Reasons:*
          - Invalid token: Try with a different jwt token.
      '403':
        description: |
          **Forbidden**  
          *Possible Reasons:*
          - Admin authorization failed: Use a token with admin privilege.
      '404':
        description: |
          **Not Found**  
          *Possible Reasons:*
          - User not found: Try with a different jwt token.
          - Path is incorrect: Check API path and try again.
      '405':
        description: |
          **Method Not Allowed**  
          *Possible Reasons:*
          - Method is not allowed: Check HTTP method and try again.
      '500':
        description: |
          **Internal Server Error**  
          *Possible Reasons:*
          - Can't connect to server: Check the connection
          - Other server errors
