tags:
  name: Auth Routes
  description: Routes specified authentication and jwt purposes.
/auth/login:
  post:
    summary: Login to get jwt
    requestBody:
      description: Login details of the user
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/User Login'
    tags: [Auth Routes]
    responses:
      '200':
        description: JWT successfully generated
        content:
          application/json:
            schema:
              type: object
              properties:
                status:
                  type: string
                  enum: ['true', 'false']
                  description: Whether the request was successful or not
                message:
                  type: string
                  description: Description of the response
                data:
                  type: object
                  properties:
                    user:
                      type: object
                      properties:
                        accessToken:
                          type: string
                          description: jwt access token
                        refreshToken:
                          type: string
                          description: jwt refresh token
                        role:
                          type: string
                          enum: [admin, agent, supervisor, qc, qa]
                          description: Role type of user
      '401':
        description: |
          **Unauthorized**  
          *Possible Reasons:*
          - Invalid email or password: Try checking email and password.
      '404':
        description: |
          **Not Found**  
          *Possible Reasons:*
          - Path is incorrect. Check API path and try again.
      '405':
        description: |
          *Method Not Allowed**  
          *Possible Reasons:*
          - Method is not allowed. Check HTTP method and try again.
      '422':
        description: |
          **Unprocessable Entity**  
          *Possible Reasons:*
          - Validation failed. Try checking the request body.
      '500':
        description: |
          **Internal Server Error**  
          *Possible Reasons:*
          - Can't connect to server: Check the connection
          - Other server errors
/auth/refresh-token:
  post:
    summary: Get a new pair of access and refresh tokens
    tags: [Auth Routes]
    requestBody:
      description: Login details of the user
      required: true
      content:
        application/json:
          schema:
            type: object
            properties:
              refreshToken:
                type: string
                description: The current jwt refresh token value
    responses:
      '200':
        description: New pair of access and refresh tokens generated
        content:
          application/json:
            schema:
              type: object
              properties:
                status:
                  type: string
                  enum: ['true', 'false']
                  description: Whether the request was successful or not
                message:
                  type: string
                  description: Description of the response
                data:
                  type: object
                  properties:
                    user:
                      type: object
                      properties:
                        accessToken:
                          type: string
                          description: New access token
                        refreshToken:
                          type: string
                          description: New refresh token
      '400':
        description: |
          **Bad Request**  
          *Possible Reasons:*  
          - Missing refresh token: Try adding jwt refresh token in request body.
      '401':
        description: |
          **Unauthorized**   
          *Possible Reasons:*
          - Invalid token: Try with a different jwt refresh token.
      '404':
        description: |
          **Not Found**  
          *Possible Reasons:*
          - Path is incorrect. Check API path and try again.
      '405':
        description: |
          *Method Not Allowed**  
          *Possible Reasons:*
          - Method is not allowed. Check HTTP method and try again.
      '500':
        description: |
          **Internal Server Error**  
          *Possible Reasons:*
          - Can't connect to server: Check the connection
          - Other server errors
